import Axios from 'axios';

export const Route = '/api/task_type';
// Generated by https://quicktype.io

export const APITaskType = (payload: Request) =>
  Axios.post<Response>(Route, payload);

export interface Request {
  task_type: Tasktype;
}

export enum Tasktype {
  抓拍 = '抓拍',
  车牌抓拍 = '车牌抓拍',
  FP = 'FP',
}
export interface Response {
  code: number;
  data: string[];
}
