stages:
  - build
  - deploy 

build:
  stage: build
  tags:
    - build
  script:
    - docker build . -t localhost:5000/fasteval-jacinth:${CI_COMMIT_SHA::8}

deploy:
  stage: deploy
  tags:
    - build
  script:
    - docker rm -f fasteval-jacinth || true
    - docker run --rm -d -p 3000:3000 --name fasteval-jacinth localhost:5000/fasteval-jacinth:${CI_COMMIT_SHA::8}
